pipeline {
	agent any
	stages {
		stage("Clean up") {
			steps {
				deleteDir()
			}
		}
		stage("Clone repo") {
			steps {
				sh "git clone repo-url"
			}
		}
		stage("build") {
			steps {
				dir("simple-java-maven-app") {
					sh "mvn clean install"
				}
			}
		}
        stage("test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
        }
	}
}